task_management/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from core.views import home, no_permission
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("users/", include('users.urls')),
    path('', home, name="home"),
    path('no-permission/', no_permission, name='no-permission')
]+debug_toolbar_urls()

# Ctrl + Shift + P
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from tasks.views import (
    ManagerDashboardView, EmployeeDashboardView, CreateTaskView, ViewTaskView, UpdateTaskView, DeleteTaskView, TaskDetailsView, DashboardView,
    Greetings, HiGreetings, HiHowGreetings, CreateTask, ViewProject, TaskDetail, UpdateTask
)

urlpatterns = [
    path('manager-dashboard/', ManagerDashboardView.as_view(), name="manager-dashboard"),
    path('user-dashboard/', EmployeeDashboardView.as_view(), name='user-dashboard'),
    path('create-task/', CreateTaskView.as_view(), name='create-task'),
    path('view_task/', ViewTaskView.as_view(), name='view-task'),
    path('task/<int:task_id>/details/', TaskDetailsView.as_view(), name='task-details'),
    path('update-task/<int:id>/', UpdateTaskView.as_view(), name='update-task'),
    path('delete-task/<int:id>/', DeleteTaskView.as_view(), name='delete-task'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('greetings/', HiHowGreetings.as_view(greetings='Hi Good Day!'), name='greetings'),
    # Legacy/other CBVs for reference
    path('create-task-cbv/', CreateTask.as_view(), name='create-task-cbv'),
    path('view-task-list/', ViewProject.as_view(), name='view-task-list'),
    path('task-detail-cbv/<int:task_id>/', TaskDetail.as_view(), name='task-detail-cbv'),
    path('update-task-cbv/<int:id>/', UpdateTask.as_view(), name='update-task-cbv'),
]

tasks/models.py
from django.db import models
from django.conf import settings


class Task(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('IN_PROGRESS', 'In Progress'),
        ('COMPLETED', 'Completed')
    ]
    project = models.ForeignKey(
        "Project",
        on_delete=models.CASCADE,
        default=1
    )
    # assigned_to = models.ManyToManyField(Employee, related_name='tasks')
    assigned_to = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='tasks')
    title = models.CharField(max_length=250)
    description = models.TextField()
    due_date = models.DateField()
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default="PENDING")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # details

    def __str__(self):
        return self.title


class TaskDetail(models.Model):
    HIGH = 'H'
    MEDIUM = 'M'
    LOW = 'L'
    PRIORITY_OPTIONS = (
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low')
    )
    task = models.OneToOneField(
        Task,
        on_delete=models.DO_NOTHING,
        related_name='details',
    )
    asset = models.ImageField(upload_to='tasks_asset',  blank=True, null=True,
                              default="tasks_asset/default_img.jpg")
    priority = models.CharField(
        max_length=1, choices=PRIORITY_OPTIONS, default=LOW)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Details form Task {self.task.title}"


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from tasks.models import Task, TaskDetail

# Django Form


class TaskForm(forms.Form):
    title = forms.CharField(max_length=250, label="Task Title")
    description = forms.CharField(
        widget=forms.Textarea, label='Task Description')
    due_date = forms.DateField(widget=forms.SelectDateWidget, label="Due Date")
    assigned_to = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple, choices=[], label='Assigned To')

    def __init__(self, *args, **kwargs):
        # print(args, kwargs)
        employees = kwargs.pop("employees", [])
        super().__init__(*args, **kwargs)
        self.fields['assigned_to'].choices = [
            (emp.id, emp.name) for emp in employees]


class StyledFormMixin:
    """ Mixing to apply style to form field"""

    def __init__(self, *arg, **kwarg):
        super().__init__(*arg, **kwarg)
        self.apply_styled_widgets()

    default_classes = "border-2 border-gray-300 w-full p-3 rounded-lg shadow-sm focus:outline-none focus:border-rose-500 focus:ring-rose-500"

    def apply_styled_widgets(self):
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.TextInput):
                field.widget.attrs.update({
                    'class': self.default_classes,
                    'placeholder': f"Enter {field.label.lower()}"
                })
            elif isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({
                    'class': f"{self.default_classes} resize-none",
                    'placeholder':  f"Enter {field.label.lower()}",
                    'rows': 5
                })
            elif isinstance(field.widget, forms.SelectDateWidget):
                # print("Inside Date")
                field.widget.attrs.update({
                    "class": "border-2 border-gray-300 p-3 rounded-lg shadow-sm focus:outline-none focus:border-rose-500 focus:ring-rose-500"
                })
            elif isinstance(field.widget, forms.CheckboxSelectMultiple):
                # print("Inside checkbox")
                field.widget.attrs.update({
                    'class': "space-y-2"
                })
            else:
                # print("Inside else")
                field.widget.attrs.update({
                    'class': self.default_classes
                })


# Django Model Form


class TaskModelForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'assigned_to']
        widgets = {
            'due_date': forms.SelectDateWidget,
            'assigned_to': forms.CheckboxSelectMultiple
        }


class TaskDetailModelForm(StyledFormMixin, forms.ModelForm):
    class Meta:
        model = TaskDetail
        fields = ['priority', 'notes', 'asset']

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tasks.forms import TaskForm, TaskModelForm, TaskDetailModelForm
from tasks.models import Task, TaskDetail, Project
from datetime import date
from django.db.models import Q, Count, Max, Min, Avg
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test, login_required, permission_required
from users.views import is_admin
from django.http import HttpResponse
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views.generic.base import ContextMixin
from django.views.generic import ListView, DetailView, UpdateView


# Class Based View Re-use example


class Greetings(View):
    greetings = 'Hello Everyone'

    def get(self, request):
        return HttpResponse(self.greetings)


class HiGreetings(Greetings):
    greetings = 'Hi Everyone'


class HiHowGreetings(Greetings):
    greetings = 'Hi Everyone, How are you'


def is_manager(user):
    return user.groups.filter(name='Manager').exists()


def is_employee(user):
    return user.groups.filter(name='Manager').exists()



class ManagerDashboardView(UserPassesTestMixin, View):
    login_url = 'no-permission'

    def test_func(self):
        return is_manager(self.request.user)

    def get(self, request):
        type = request.GET.get('type', 'all')
        counts = Task.objects.aggregate(
            total=Count('id'),
            completed=Count('id', filter=Q(status='COMPLETED')),
            in_progress=Count('id', filter=Q(status='IN_PROGRESS')),
            pending=Count('id', filter=Q(status='PENDING')),
        )
        base_query = Task.objects.select_related('details').prefetch_related('assigned_to')
        if type == 'completed':
            tasks = base_query.filter(status='COMPLETED')
        elif type == 'in-progress':
            tasks = base_query.filter(status='IN_PROGRESS')
        elif type == 'pending':
            tasks = base_query.filter(status='PENDING')
        elif type == 'all':
            tasks = base_query.all()
        context = {
            "tasks": tasks,
            "counts": counts,
            "role": 'manager'
        }
        return render(request, "dashboard/manager-dashboard.html", context)



class EmployeeDashboardView(UserPassesTestMixin, View):
    login_url = 'no-permission'

    def test_func(self):
        return is_employee(self.request.user)

    def get(self, request):
        return render(request, "dashboard/user-dashboard.html")



class CreateTaskView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'tasks.add_task'
    login_url = 'no-permission'
    template_name = 'task_form.html'

    def get(self, request):
        task_form = TaskModelForm()
        task_detail_form = TaskDetailModelForm()
        context = {"task_form": task_form, "task_detail_form": task_detail_form}
        return render(request, self.template_name, context)

    def post(self, request):
        task_form = TaskModelForm(request.POST)
        task_detail_form = TaskDetailModelForm(request.POST, request.FILES)
        if task_form.is_valid() and task_detail_form.is_valid():
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()
            messages.success(request, "Task Created Successfully")
            return redirect('create-task')
        context = {"task_form": task_form, "task_detail_form": task_detail_form}
        return render(request, self.template_name, context)


create_decorators = [login_required, permission_required(
    "tasks.add_task", login_url='no-permission')]


class CreateTask(ContextMixin, LoginRequiredMixin, PermissionRequiredMixin, View):
    """ For creating task """
    permission_required = 'tasks.add_task'
    login_url = 'sign-in'
    template_name = 'task_form.html'

    """ 
    0. Create Task
    1. LoginRequiredMixin
    2. PermissionRequiredMixin
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_form'] = kwargs.get('task_form', TaskModelForm())
        context['task_detail_form'] = kwargs.get(
            'task_detail_form', TaskDetailModelForm())
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        task_form = TaskModelForm(request.POST)
        task_detail_form = TaskDetailModelForm(request.POST, request.FILES)

        if task_form.is_valid() and task_detail_form.is_valid():

            """ For Model Form Data """
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()

            messages.success(request, "Task Created Successfully")
            context = self.get_context_data(
                task_form=task_form, task_detail_form=task_detail_form)
            return render(request, self.template_name, context)



class UpdateTaskView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'tasks.change_task'
    login_url = 'no-permission'
    template_name = 'task_form.html'

    def get(self, request, id):
        task = Task.objects.get(id=id)
        task_form = TaskModelForm(instance=task)
        task_detail_form = TaskDetailModelForm(instance=getattr(task, 'details', None))
        context = {"task_form": task_form, "task_detail_form": task_detail_form}
        return render(request, self.template_name, context)

    def post(self, request, id):
        task = Task.objects.get(id=id)
        task_form = TaskModelForm(request.POST, instance=task)
        task_detail_form = TaskDetailModelForm(request.POST, request.FILES, instance=getattr(task, 'details', None))
        if task_form.is_valid() and task_detail_form.is_valid():
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()
            messages.success(request, "Task Updated Successfully")
            return redirect('update-task', id)
        context = {"task_form": task_form, "task_detail_form": task_detail_form}
        return render(request, self.template_name, context)


class UpdateTask(UpdateView):
    model = Task
    form_class = TaskModelForm
    template_name = 'task_form.html'
    context_object_name = 'task'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_form'] = self.get_form()
        # print(context)
        if hasattr(self.object, 'details') and self.object.details:
            context['task_detail_form'] = TaskDetailModelForm(
                instance=self.object.details)
        else:
            context['task_detail_form'] = TaskDetailModelForm()

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        task_form = TaskModelForm(request.POST, instance=self.object)

        task_detail_form = TaskDetailModelForm(
            request.POST, request.FILES, instance=getattr(self.object, 'details', None))

        if task_form.is_valid() and task_detail_form.is_valid():

            """ For Model Form Data """
            task = task_form.save()
            task_detail = task_detail_form.save(commit=False)
            task_detail.task = task
            task_detail.save()

            messages.success(request, "Task Updated Successfully")
            return redirect('update-task', self.object.id)
        return redirect('update-task', self.object.id)



class DeleteTaskView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'tasks.delete_task'
    login_url = 'no-permission'

    def post(self, request, id):
        task = Task.objects.get(id=id)
        task.delete()
        messages.success(request, 'Task Deleted Successfully')
        return redirect('manager-dashboard')

    def get(self, request, id):
        messages.error(request, 'Something went wrong')
        return redirect('manager-dashboard')



class ViewTaskView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'tasks.view_task'
    login_url = 'no-permission'
    template_name = 'show_task.html'

    def get(self, request):
        projects = Project.objects.annotate(num_task=Count('task')).order_by('num_task')
        return render(request, self.template_name, {"projects": projects})


view_project_decorators = [login_required, permission_required(
    "projects.view_project", login_url='no-permission')]


@method_decorator(view_project_decorators, name='dispatch')
class ViewProject(ListView):
    model = Project
    context_object_name = 'projects'
    template_name = 'show_task.html'

    def get_queryset(self):
        queryset = Project.objects.annotate(
            num_task=Count('task')).order_by('num_task')
        return queryset



class TaskDetailsView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'tasks.view_task'
    login_url = 'no-permission'
    template_name = 'task_details.html'

    def get(self, request, task_id):
        task = Task.objects.get(id=task_id)
        status_choices = Task.STATUS_CHOICES
        return render(request, self.template_name, {"task": task, 'status_choices': status_choices})

    def post(self, request, task_id):
        task = Task.objects.get(id=task_id)
        selected_status = request.POST.get('task_status')
        task.status = selected_status
        task.save()
        return redirect('task-details', task.id)


class TaskDetail(DetailView):
    model = Task

tasks/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="m-8">
    <!-- Header -->
    <header class="flex justify-between items-center m-4">
        <h1 class="text-xl font-bold">Dashboard</h1>
        <div class="flex gap-2">
            <button class="rounded-full hover:bg-gray-200 p-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
                </svg>
            </button>
            <button class="rounded-full bg-blue-500 w-10 text-white">B</button>
        </div>
    </header>

    <!-- Stats grid -->
    <div class="grid grid-cols-4 gap-4 mb-8">

        <a href='{% url "manager_dashboard" %}?type=completed'>
        <div class="rounded-xl p-4 gap-2 shadow-xl"> <!-- card div --> 
            <h3 class="text-gray-500 font-medium mb-1">Total task</h3>
            <div class="flex justify-between items-center">
                <p class="text-xl font-bold"> {{ total_task }} </p>
                <div class="rounded-full bg-blue-200 flex items-center p-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-blue-600">
                    <path stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                    </svg>
                </div>
            </div>
            <div class="text-gray-500 text-sm">11 last month</div> 
        </div>
        </a>

        <a href='{% url "manager_dashboard" %}?type=completed'>
            <div class="rounded-xl p-4 gap-2 shadow-xl"> <!-- card div --> 
                <h3 class="text-gray-500 font-medium mb-1">Completed Task</h3>
                <div class="flex justify-between items-center">
                    <p class="text-xl font-bold"> {{ completed_task }} </p>
                    <div class="rounded-full bg-green-200 flex items-center p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-green-600">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>
                    </div>
                </div>
                <div class="text-gray-500 text-sm">11 last month</div> 
            </div>
        </a>

        <a href='{% url "manager_dashboard" %}?type=in-progess'>
            <div class="rounded-xl p-4 gap-2 shadow-xl"> <!-- card div --> 
                <h3 class="text-gray-500 font-medium mb-1">Task in Progress</h3>
                <div class="flex justify-between items-center">
                    <p class="text-xl font-bold"> {{ in_progress_task }} </p>
                    <div class="rounded-full bg-yellow-200 flex items-center p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-yellow-600">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>
                    </div>
                </div>
                <div class="text-gray-500 text-sm">11 last month</div> 
            </div>
        </a>

        <a href='{% url "manager_dashboard" %}?type=todo'>
        <div class="rounded-xl p-4 gap-2 shadow-xl"> <!-- card div --> 
            <h3 class="text-gray-500 font-medium mb-1">TODO</h3>
            <div class="flex justify-between items-center">
                {% comment %} try creating custom filters {% endcomment %}
                {% comment %} <p class="text-xl font-bold">{{ total_task|subtract:completed_task }}</p> {% endcomment %}
                <p class="text-xl font-bold">{{ pending_task }}</p>
                <div class="rounded-full bg-pink-200 flex items-center p-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-pink-600">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                    </svg>
                </div>
            </div>
            <div class="text-gray-500 text-sm">11 last month</div> 
        </div>
        </a>
        
    </div>

    <ul>
        {% if messages %}
            {% for message in messages %}
                <li class="px-2 py-1 bg-green-50 ">{{message}}</li>
            {% endfor %}
        {% endif %}
    </ul>
    {% block task_list %}{% endblock task_list %}
</body>
</html>

tasks/templates/manager_dashboard.html
{% extends "dashboard.html" %}

{% block task_list %}
<!-- task table -->
    <div>
        <!-- task column -->
        <div class="flex justify-between p-4 grid grid-cols-6 text-gray-500 font-bold">
            <div>TASK TITKE</div>
            <div>PRIORITY</div>
            <div>TEAM</div>
            <div>STATUS</div>
            <div>CREATED AT</div>
            <div>ACTIONS</div>
        </div>

        <!-- actual task -->
        {% for t in tasks%}
        <div class="grid grid-cols-6 items-center"><!-- task-item -->
            <div class="flex items-center gap-2">
                <div class="rounded-full bg-green-500 w-2 h-2"></div>
                <div class=""> {{t.id}}. {{ t.title }} </div>
            </div>
            <!-- PRIORITY -->
            <div class="flex">
                <span class="rounded-lg font-semibold bg-blue-100 text-blue-600 p-2">{{t.details.get_priority_display}}</span>
            </div>
            <div class="flex -space-x-2 m-1"><!-- team -->
                {% for e in t.assigned_to.all %}
                <div class="rounded-full text-white bg-blue-500 p-2 text-sm"> {{ e.username|slice:":2"|upper }} </div>
                {% endfor %}
            </div>
            {% comment %} STATUS {% endcomment %}
            <div class=""> {{ t.status }} </div>
            <!-- CREATED -->
            <div class="text-sm text-gray-500"> {{ t.created_at|timesince }} </div>
    
            <div>
                <a href="{% url 'update-task' t.id %}">
                    <button class="rounded-full hover:bg-gray-200 p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                            <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                        </svg>
                    </button>
                </a>

                <form action="{% url 'delete-task' t.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button class="rounded-full hover:bg-gray-200 p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                        </svg>
                    </button>
                </form>
            </div>

        </div>
        {% endfor %}
    </div>
{% endblock task_list %}

tasks/templates/show_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
       <ol>
            {% for project in projects %}
                <li>
                    <p>{{project.name}}</p>
                    <p>{{project.num_task}}</p>
                </li>
            {% endfor %}
            </ol> 
            {% comment %} <p>{{task_count}}</p> {% endcomment %}
    </div>
</body>
</html>

tasks/templates/task_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
</head>
<body>
    <div class="w-1/2 mx-auto mt-8">
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="px-2 py-1 {% if message.tags == 'success' %}bg-green-500{% endif %} ">{{message}}</div>
                {% endfor %}
            {% endif %}
        </div>
        <form method="POST" enctype='multipart/form-data'>
            
            {% csrf_token %}
            {{ task_form }}
            {{ task_detail_form }}
            <button type="submit" class="mb-5 bg-rose-600 px-3 py-2 text-white mt-2 rounded-md">Submit</button>
        </form>
    </div>
</body>
</html>

tasks/templates/taskform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body>
    <div class="w-1/2 mx-auto mt-8">
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="px-2 py-1 {% if message.tags == 'success' %}bg-green-500{% endif %} ">{{message}}</div>
                {% endfor %}
            {% endif %}
        </div>
        <form method="POST" enctype='multipart/form-data'>
            
            {% csrf_token %}
            {{ task_form }}
            {{ task_detail_form }}
            <button type="submit" class="mb-5 bg-rose-600 px-3 py-2 text-white mt-2 rounded-md">Submit</button>
        </form>
    </div>
</body>
</html>